### ISSUE TITLE
HW 09_10_2017

### ISSUE THREAD

**Issue by Kiolk** [IstiN/android-training-2017#61]
Home work 09.10.2017 https://github.com/Kiolk/MyJSON
In main_activity.class I implement my example of parsing from JSON file, and present result in ListView.
In MyJSONTest I covered by test every point of home task. Different way of parsing JSON file present in classes: MockJson, GSONUserAdapter, MyJSONTest.

**Comment by ilya-shknaj** [comment]
HW implemented, but I found issues that don't related to current HW : 

GsonUsers.java you shouldn't create new ArrayList. Declare field is enough
you can use libraries like okhttp and volley for some homework, but you can't use it for your project.
Better avoid use Pair class, because in most cases it not clear what mean first and second param.
Static MyFavoriteWriterApi in asynctask is bad architecture
GSONUserAdapter contain duplicate values like "name". Better create constants for it
HttpAsyncTaskOtherClass line 38 WTF? 
HttpAsyncTaskOtherClass parse json in UI thread
HttpAsyncTaskOtherClass Toast in cycle ? It's not user friendly. Use log
HttpAsyncTaskOtherClass partially duplicate HttpClient
MyJSONTest very difficult to read and understand

**Comment by Kiolk** [comment]
Thanks for comment. 
Sorry for unreadable code, becouse I created many mistakes and unworked methods befor find correct solution. I forgot clean it. In future, I keep in my mind, that my cod must be simple for readble for other person becouse it's very important moment in team work.
